name: Java Maven CI

on: [push]

defaults:
  run:
    shell: bash
    working-directory: java-mvn

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '13', '15' ]
    name: Java ${{ matrix.Java }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Maven Verify
        run: mvn --batch-mode verify
